# Generated by Django 4.2 on 2023-04-21 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclubuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_level', models.CharField(choices=[('A', 'Adult'), ('J', 'Junior'), ('C', 'Concession')], default='A', max_length=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
